export const SELECT_ANSWER = 'SELECT_ANSWER';


export const FETCH_QUESTION_BEGIN = 'FETCH_QUESTION';
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';
export const FETCH_QUESTION_FAILURE = 'FETCH_QUESTION_FAILURE';

export const FETCH_ANSWERS_BEGIN = 'FETCH_ANSWERS';
export const FETCH_ANSWERS_SUCCESS = 'FETCH_ANSWERS_SUCCESS';
export const FETCH_ANSWERS_FAILURE = 'FETCH_ANSWERS_FAILURE';

export const SUBMIT_ANSWER_BEGIN = 'SUBMIT_ANSWER';
export const SUBMIT_ANSWER_SUCCESS = 'SUBMIT_ANSWER_SUCCESS';
export const SUBMIT_ANSWER_FAILURE = 'SUBMIT_ANSWER_FAILURE';

export const FETCH_ALL_FORESTS_BEGIN = 'FETCH_ALL_FORESTS_BEGIN';
export const FETCH_ALL_FORESTS_SUCCESS = 'FETCH_ALL_FORESTS_SUCCESS';
export const FETCH_ALL_FORESTS_FAILURE = 'FETCH_ALL_FORESTS_FAILURE';

export const FETCH_FOREST_BEGIN = 'FETCH_FOREST_BEGIN';
export const FETCH_FOREST_SUCCESS = 'FETCH_FOREST_SUCCESS';
export const FETCH_FOREST_FAILURE = 'FETCH_FOREST_FAILURE';